### ISSUE TITLE
Fungsi nuget.config di folder solution item

### ISSUE THREAD

**Issue by Azzammi** [k4m4r82/DemoLog4Net#1]
Apakah nuget.config itu kita create sendiri apa code generated ?
Dan kalau memang create sendiri fungsinya seperti apa dan bagaimana menggunakannya ?

**Comment by k4m4r82** [comment]
> Apakah nuget.config itu kita create sendiri apa code generated ?

Iya dibuat manual, hanya menggunakan format xml biasa

> Dan kalau memang create sendiri fungsinya seperti apa dan bagaimana menggunakannya ?

Ya tergantung kebutuhan, misal secara default ketika kita menambahkan paket nuget, semua librarynya otomatis tersimpan di folder packages masing2x project, jadi klo kita punya 1 solution dg 5 project berarti kita juga punya 5 folder packages di masing-masing project. Pada hal masing-masing project ini mungkin ada yg menggunakan paket nuget sama dan tentunya ini pemborosan penyimpanan data, nah akan lebih baik semua paket nuget yg dipake kita simpan di satu folder yg sama misal dengan nama **lib**, di dalam folder solution, jadi semua project mereferensi ke folder yang sama yaitu **lib**. Nah untuk merubahan **behavior** ini kita gunakan file nuget.config. Untuk referensi lengkapnya bisa om cek di[sini](https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file).

**Comment by Azzammi** [comment]
Sip dah om, nnti ane coba lgi. Secara teori nya sih ngerti, tapi implementasinya belum cukup paham. Thanks om
